server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: job-api
          uri: lb://OPPORTUNITY-JOB
          predicates:
            - Path=/v1/api/jobs/**
        - id: auth-api
          uri: lb://OPPORTUNITY-AUTH
          predicates:
            - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG