server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: job-api
          uri: http://localhost:8081/v1/api/jobs
          predicates:
            - Path=v1/api/jobs/**
        - id: auth-api
          uri: http://localhost:8082/auth
          predicates:
            - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG